/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as NameSearchWorkerImport } from './routes/name-search/worker'
import { Route as NameSearchClientImport } from './routes/name-search/client'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NameSearchWorkerRoute = NameSearchWorkerImport.update({
  id: '/name-search/worker',
  path: '/name-search/worker',
  getParentRoute: () => rootRoute,
} as any)

const NameSearchClientRoute = NameSearchClientImport.update({
  id: '/name-search/client',
  path: '/name-search/client',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/name-search/client': {
      id: '/name-search/client'
      path: '/name-search/client'
      fullPath: '/name-search/client'
      preLoaderRoute: typeof NameSearchClientImport
      parentRoute: typeof rootRoute
    }
    '/name-search/worker': {
      id: '/name-search/worker'
      path: '/name-search/worker'
      fullPath: '/name-search/worker'
      preLoaderRoute: typeof NameSearchWorkerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/name-search/client': typeof NameSearchClientRoute
  '/name-search/worker': typeof NameSearchWorkerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/name-search/client': typeof NameSearchClientRoute
  '/name-search/worker': typeof NameSearchWorkerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/name-search/client': typeof NameSearchClientRoute
  '/name-search/worker': typeof NameSearchWorkerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/name-search/client' | '/name-search/worker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/name-search/client' | '/name-search/worker'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/name-search/client'
    | '/name-search/worker'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NameSearchClientRoute: typeof NameSearchClientRoute
  NameSearchWorkerRoute: typeof NameSearchWorkerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NameSearchClientRoute: NameSearchClientRoute,
  NameSearchWorkerRoute: NameSearchWorkerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/name-search/client",
        "/name-search/worker"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/name-search/client": {
      "filePath": "name-search/client.tsx"
    },
    "/name-search/worker": {
      "filePath": "name-search/worker.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
